cp /extra/wayne1/preserve/BioGRID/networks/Entrez/4.4.206/RN-SP-RN.el /home/wangph1/plant/networks/bgind/RN-SP-RN.el
cp /extra/wayne1/preserve/BioGRID/networks/Entrez/4.4.206/RN-SP-SP.el /home/wangph1/plant/networks/bgind/RN-SP-SP.el
cp /extra/wayne1/preserve/BioGRID/networks/Entrez/4.4.206/RN-SC-RN.el /home/wangph1/plant/networks/bgind/RN-SC-RN.el
cp /extra/wayne1/preserve/BioGRID/networks/Entrez/4.4.206/RN-SC-SC.el /home/wangph1/plant/networks/bgind/RN-SC-SC.el
cp /extra/wayne1/preserve/BioGRID/networks/Entrez/4.4.206/RN-CE-RN.el /home/wangph1/plant/networks/bgind/RN-CE-RN.el
cp /extra/wayne1/preserve/BioGRID/networks/Entrez/4.4.206/RN-CE-CE.el /home/wangph1/plant/networks/bgind/RN-CE-CE.el
cp /extra/wayne1/preserve/BioGRID/networks/Entrez/4.4.206/RN-DM-RN.el /home/wangph1/plant/networks/bgind/RN-DM-RN.el
cp /extra/wayne1/preserve/BioGRID/networks/Entrez/4.4.206/RN-DM-DM.el /home/wangph1/plant/networks/bgind/RN-DM-DM.el
cp /extra/wayne1/preserve/BioGRID/networks/Entrez/4.4.206/RN-MM-RN.el /home/wangph1/plant/networks/bgind/RN-MM-RN.el
cp /extra/wayne1/preserve/BioGRID/networks/Entrez/4.4.206/RN-MM-MM.el /home/wangph1/plant/networks/bgind/RN-MM-MM.el
cp /extra/wayne1/preserve/BioGRID/networks/Entrez/4.4.206/RN-AT-RN.el /home/wangph1/plant/networks/bgind/RN-AT-RN.el
cp /extra/wayne1/preserve/BioGRID/networks/Entrez/4.4.206/RN-AT-AT.el /home/wangph1/plant/networks/bgind/RN-AT-AT.el
cp /extra/wayne1/preserve/BioGRID/networks/Entrez/4.4.206/RN-HS-RN.el /home/wangph1/plant/networks/bgind/RN-HS-RN.el
cp /extra/wayne1/preserve/BioGRID/networks/Entrez/4.4.206/RN-HS-HS.el /home/wangph1/plant/networks/bgind/RN-HS-HS.el
cp /extra/wayne1/preserve/BioGRID/networks/Entrez/4.4.206/SP-SC-SP.el /home/wangph1/plant/networks/bgind/SP-SC-SP.el
cp /extra/wayne1/preserve/BioGRID/networks/Entrez/4.4.206/SP-SC-SC.el /home/wangph1/plant/networks/bgind/SP-SC-SC.el
cp /extra/wayne1/preserve/BioGRID/networks/Entrez/4.4.206/SP-CE-SP.el /home/wangph1/plant/networks/bgind/SP-CE-SP.el
cp /extra/wayne1/preserve/BioGRID/networks/Entrez/4.4.206/SP-CE-CE.el /home/wangph1/plant/networks/bgind/SP-CE-CE.el
cp /extra/wayne1/preserve/BioGRID/networks/Entrez/4.4.206/SP-DM-SP.el /home/wangph1/plant/networks/bgind/SP-DM-SP.el
cp /extra/wayne1/preserve/BioGRID/networks/Entrez/4.4.206/SP-DM-DM.el /home/wangph1/plant/networks/bgind/SP-DM-DM.el
cp /extra/wayne1/preserve/BioGRID/networks/Entrez/4.4.206/SP-MM-SP.el /home/wangph1/plant/networks/bgind/SP-MM-SP.el
cp /extra/wayne1/preserve/BioGRID/networks/Entrez/4.4.206/SP-MM-MM.el /home/wangph1/plant/networks/bgind/SP-MM-MM.el
cp /extra/wayne1/preserve/BioGRID/networks/Entrez/4.4.206/SP-AT-SP.el /home/wangph1/plant/networks/bgind/SP-AT-SP.el
cp /extra/wayne1/preserve/BioGRID/networks/Entrez/4.4.206/SP-AT-AT.el /home/wangph1/plant/networks/bgind/SP-AT-AT.el
cp /extra/wayne1/preserve/BioGRID/networks/Entrez/4.4.206/SP-HS-SP.el /home/wangph1/plant/networks/bgind/SP-HS-SP.el
cp /extra/wayne1/preserve/BioGRID/networks/Entrez/4.4.206/SP-HS-HS.el /home/wangph1/plant/networks/bgind/SP-HS-HS.el
cp /extra/wayne1/preserve/BioGRID/networks/Entrez/4.4.206/SC-CE-SC.el /home/wangph1/plant/networks/bgind/SC-CE-SC.el
cp /extra/wayne1/preserve/BioGRID/networks/Entrez/4.4.206/SC-CE-CE.el /home/wangph1/plant/networks/bgind/SC-CE-CE.el
cp /extra/wayne1/preserve/BioGRID/networks/Entrez/4.4.206/SC-DM-SC.el /home/wangph1/plant/networks/bgind/SC-DM-SC.el
cp /extra/wayne1/preserve/BioGRID/networks/Entrez/4.4.206/SC-DM-DM.el /home/wangph1/plant/networks/bgind/SC-DM-DM.el
cp /extra/wayne1/preserve/BioGRID/networks/Entrez/4.4.206/SC-MM-SC.el /home/wangph1/plant/networks/bgind/SC-MM-SC.el
cp /extra/wayne1/preserve/BioGRID/networks/Entrez/4.4.206/SC-MM-MM.el /home/wangph1/plant/networks/bgind/SC-MM-MM.el
cp /extra/wayne1/preserve/BioGRID/networks/Entrez/4.4.206/SC-AT-SC.el /home/wangph1/plant/networks/bgind/SC-AT-SC.el
cp /extra/wayne1/preserve/BioGRID/networks/Entrez/4.4.206/SC-AT-AT.el /home/wangph1/plant/networks/bgind/SC-AT-AT.el
cp /extra/wayne1/preserve/BioGRID/networks/Entrez/4.4.206/SC-HS-SC.el /home/wangph1/plant/networks/bgind/SC-HS-SC.el
cp /extra/wayne1/preserve/BioGRID/networks/Entrez/4.4.206/SC-HS-HS.el /home/wangph1/plant/networks/bgind/SC-HS-HS.el
cp /extra/wayne1/preserve/BioGRID/networks/Entrez/4.4.206/CE-DM-CE.el /home/wangph1/plant/networks/bgind/CE-DM-CE.el
cp /extra/wayne1/preserve/BioGRID/networks/Entrez/4.4.206/CE-DM-DM.el /home/wangph1/plant/networks/bgind/CE-DM-DM.el
cp /extra/wayne1/preserve/BioGRID/networks/Entrez/4.4.206/CE-MM-CE.el /home/wangph1/plant/networks/bgind/CE-MM-CE.el
cp /extra/wayne1/preserve/BioGRID/networks/Entrez/4.4.206/CE-MM-MM.el /home/wangph1/plant/networks/bgind/CE-MM-MM.el
cp /extra/wayne1/preserve/BioGRID/networks/Entrez/4.4.206/CE-AT-CE.el /home/wangph1/plant/networks/bgind/CE-AT-CE.el
cp /extra/wayne1/preserve/BioGRID/networks/Entrez/4.4.206/CE-AT-AT.el /home/wangph1/plant/networks/bgind/CE-AT-AT.el
cp /extra/wayne1/preserve/BioGRID/networks/Entrez/4.4.206/CE-HS-CE.el /home/wangph1/plant/networks/bgind/CE-HS-CE.el
cp /extra/wayne1/preserve/BioGRID/networks/Entrez/4.4.206/CE-HS-HS.el /home/wangph1/plant/networks/bgind/CE-HS-HS.el
cp /extra/wayne1/preserve/BioGRID/networks/Entrez/4.4.206/DM-MM-DM.el /home/wangph1/plant/networks/bgind/DM-MM-DM.el
cp /extra/wayne1/preserve/BioGRID/networks/Entrez/4.4.206/DM-MM-MM.el /home/wangph1/plant/networks/bgind/DM-MM-MM.el
cp /extra/wayne1/preserve/BioGRID/networks/Entrez/4.4.206/DM-AT-DM.el /home/wangph1/plant/networks/bgind/DM-AT-DM.el
cp /extra/wayne1/preserve/BioGRID/networks/Entrez/4.4.206/DM-AT-AT.el /home/wangph1/plant/networks/bgind/DM-AT-AT.el
cp /extra/wayne1/preserve/BioGRID/networks/Entrez/4.4.206/DM-HS-DM.el /home/wangph1/plant/networks/bgind/DM-HS-DM.el
cp /extra/wayne1/preserve/BioGRID/networks/Entrez/4.4.206/DM-HS-HS.el /home/wangph1/plant/networks/bgind/DM-HS-HS.el
cp /extra/wayne1/preserve/BioGRID/networks/Entrez/4.4.206/MM-AT-MM.el /home/wangph1/plant/networks/bgind/MM-AT-MM.el
cp /extra/wayne1/preserve/BioGRID/networks/Entrez/4.4.206/MM-AT-AT.el /home/wangph1/plant/networks/bgind/MM-AT-AT.el
cp /extra/wayne1/preserve/BioGRID/networks/Entrez/4.4.206/MM-HS-MM.el /home/wangph1/plant/networks/bgind/MM-HS-MM.el
cp /extra/wayne1/preserve/BioGRID/networks/Entrez/4.4.206/MM-HS-HS.el /home/wangph1/plant/networks/bgind/MM-HS-HS.el
cp /extra/wayne1/preserve/BioGRID/networks/Entrez/4.4.206/AT-HS-AT.el /home/wangph1/plant/networks/bgind/AT-HS-AT.el
cp /extra/wayne1/preserve/BioGRID/networks/Entrez/4.4.206/AT-HS-HS.el /home/wangph1/plant/networks/bgind/AT-HS-HS.el
